services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Command\SearchCommand:
        tags:
            - { name: console.command, command: 'dynamic-search:run' }

    DynamicSearchBundle\Command\QueuedDataCommand:
        tags:
            - { name: console.command, command: 'dynamic-search:check-queue' }