services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\EventSubscriber\DynamicSearchEventSubscriber: ~

    DynamicSearchBundle\EventDispatcher\DynamicSearchEventDispatcher: ~
