services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\EventSubscriber\DataProcessingEventSubscriber: ~

    DynamicSearchBundle\EventSubscriber\ErrorEventSubscriber: ~

    DynamicSearchBundle\EventDispatcher\DynamicSearchEventDispatcher: ~

    DynamicSearchBundle\EventListener\PimcoreElementListener:
        tags:
            - { name: kernel.event_subscriber }