services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Manager\DataManager: ~

    DynamicSearchBundle\Manager\TransformerManager: ~

    DynamicSearchBundle\Manager\IndexManager: ~

    DynamicSearchBundle\Manager\OutputChannelManager: ~

    DynamicSearchBundle\Manager\DocumentDefinitionManager: ~

    DynamicSearchBundle\Manager\NormalizerManager: ~

    DynamicSearchBundle\Manager\QueueManager: ~

    DynamicSearchBundle\Manager\ProviderBundleManager: ~
