services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Manager\DataManager: ~

    DynamicSearchBundle\Manager\TransformerManager: ~

    DynamicSearchBundle\Manager\IndexManager: ~
