services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Manager\DataManager: ~

    DynamicSearchBundle\Manager\DataTransformerManager: ~

    DynamicSearchBundle\Manager\IndexManager: ~