services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Registry\DataProviderRegistry: ~

    DynamicSearchBundle\Registry\IndexProviderRegistry: ~

    DynamicSearchBundle\Registry\TransformerRegistry: ~

    DynamicSearchBundle\Registry\IndexFieldRegistry: ~

    DynamicSearchBundle\Registry\OutputChannelRegistry: ~

    DynamicSearchBundle\Registry\DocumentDefinitionBuilderRegistry: ~

    DynamicSearchBundle\Registry\ResourceNormalizerRegistry: ~