services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Registry\DataProviderRegistry: ~

    DynamicSearchBundle\Registry\IndexProviderRegistry: ~

    DynamicSearchBundle\Registry\TransformerRegistry: ~

    DynamicSearchBundle\Registry\IndexRegistry: ~

    DynamicSearchBundle\Registry\OutputChannelRegistry: ~

    DynamicSearchBundle\Registry\DefinitionBuilderRegistry: ~

    DynamicSearchBundle\Registry\ResourceNormalizerRegistry: ~

    DynamicSearchBundle\Registry\ContextGuardRegistry: ~