services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Serializer\OutputChannelResultNormalizer:
        tags:
            - {name: 'serializer.normalizer', priority: 500 }
