services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # configuration
    DynamicSearchBundle\Configuration\Configuration: ~

    DynamicSearchBundle\Tool\Install:
        public: true
        calls:
            - [setProviderBundleManager, ['@DynamicSearchBundle\Manager\ProviderBundleManager']]
        arguments:
            $bundle: "@=service('kernel').getBundle('DynamicSearchBundle')"