services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # configuration
    DynamicSearchBundle\Configuration\Configuration: ~

    DynamicSearchBundle\Tool\Install:
        arguments:
            $bundle: "@=service('kernel').getBundle('DynamicSearchBundle')"