services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Resolver\DocumentDefinitionResolver: ~

    DynamicSearchBundle\Resolver\DocumentTransformerResolver: ~