services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Resolver\DataTransformerResolver:

    DynamicSearchBundle\Transformer\HttpResponseHtmlDataTransformer:
        tags:
            - { name: dynamic_search.data_transformer, priority: 10 }

    DynamicSearchBundle\Transformer\HttpResponsePdfDataTransformer:
        tags:
            - { name: dynamic_search.data_transformer, priority: 5 }