dynamic_search.controller.admin.get_state:
    path: /admin/dynamic-search/settings/state
    defaults: { _controller: DynamicSearchBundle\Controller\Admin\SettingsController::stateAction }
dynamic_search.controller.admin.get_logs:
    path: /admin/dynamic-search/settings/logs
    defaults: { _controller: DynamicSearchBundle\Controller\Admin\SettingsController::logAction }

dynamic_search.controller.json_search:
    path: /dynamic-search/{contextName}/j-{outputChannelName}
    defaults: { _controller: DynamicSearchBundle\Controller\SearchController::jsonSearchAction }