imports:
    - { resource: services/*.yml }

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DynamicSearchBundle\Processor\ContextWorkflowProcessor: ~

    DynamicSearchBundle\Processor\TransformerWorkflowProcessor: ~

    DynamicSearchBundle\Processor\OutputChannelWorkflowProcessor: ~

    DynamicSearchBundle\Service\LockService: ~

    DynamicSearchBundle\Service\LongProcessService: ~